import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import type { ApiResponse, PaginatedResponse } from "@/types/api";
import type { ShipmentStatus } from "@/types/enums";
import type {
  Shipment,
  ShipmentWithRelations,
  CreateShipmentInput,
  PublicTrackingData,
} from "@/types/shipment";

export type ListShipmentsFilters = {
  status?: ShipmentStatus;
  customer_id?: string;
  origin_pickup_point_id?: string;
  destination_pickup_point_id?: string;
  search?: string;
  page?: number;
  pageSize?: number;
};

export async function createShipment(
  customerId: string,
  input: CreateShipmentInput
): Promise<ApiResponse<Shipment>> {
  // Uses the admin client (service_role) to bypass RLS — this is called only
  // from the Stripe webhook handler (server-side, after payment confirmation).
  // tracking_id is auto-generated by the DB trigger (generate_tracking_id).
  // qr_code_url is set in a follow-up update after QR generation.
  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from("shipments")
    .insert({
      customer_id: customerId,
      ...input,
    })
    .select()
    .single();

  if (error) {
    return { data: null, error: { message: error.message, status: 500 } };
  }

  return { data, error: null };
}

export async function setShipmentQrCodeUrl(
  shipmentId: string,
  qrCodeUrl: string
): Promise<ApiResponse<Shipment>> {
  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from("shipments")
    .update({ qr_code_url: qrCodeUrl })
    .eq("id", shipmentId)
    .select()
    .single();

  if (error) {
    return { data: null, error: { message: error.message, status: 500 } };
  }

  return { data, error: null };
}

export async function getShipmentById(
  shipmentId: string
): Promise<ApiResponse<ShipmentWithRelations>> {
  const supabase = await createClient();

  const { data, error } = await supabase
    .from("shipments")
    .select(
      "*, origin_pickup_point:pickup_points!shipments_origin_pickup_point_id_fkey(*), destination_pickup_point:pickup_points!shipments_destination_pickup_point_id_fkey(*), customer:profiles(*), scan_logs(*)"
    )
    .eq("id", shipmentId)
    .single();

  if (error) {
    return {
      data: null,
      error: { message: "Shipment not found", code: "NOT_FOUND", status: 404 },
    };
  }

  return { data: data as unknown as ShipmentWithRelations, error: null };
}

export async function getShipmentByTrackingId(
  trackingId: string
): Promise<ApiResponse<ShipmentWithRelations>> {
  const supabase = await createClient();

  const { data, error } = await supabase
    .from("shipments")
    .select(
      "*, origin_pickup_point:pickup_points!shipments_origin_pickup_point_id_fkey(*), destination_pickup_point:pickup_points!shipments_destination_pickup_point_id_fkey(*), customer:profiles(*), scan_logs(*)"
    )
    .eq("tracking_id", trackingId)
    .single();

  if (error) {
    return {
      data: null,
      error: { message: "Shipment not found", code: "NOT_FOUND", status: 404 },
    };
  }

  return { data: data as unknown as ShipmentWithRelations, error: null };
}

export async function listShipments(
  filters: ListShipmentsFilters = {}
): Promise<ApiResponse<PaginatedResponse<Shipment>>> {
  const {
    status,
    customer_id,
    origin_pickup_point_id,
    destination_pickup_point_id,
    search,
    page = 1,
    pageSize = 20,
  } = filters;

  const supabase = await createClient();

  let query = supabase
    .from("shipments")
    .select("*", { count: "exact" })
    .order("created_at", { ascending: false })
    .range((page - 1) * pageSize, page * pageSize - 1);

  if (status) query = query.eq("status", status);
  if (customer_id) query = query.eq("customer_id", customer_id);
  if (origin_pickup_point_id) query = query.eq("origin_pickup_point_id", origin_pickup_point_id);
  if (destination_pickup_point_id)
    query = query.eq("destination_pickup_point_id", destination_pickup_point_id);
  if (search) query = query.ilike("tracking_id", `%${search}%`);

  const { data, error, count } = await query;

  if (error) {
    return { data: null, error: { message: error.message, status: 500 } };
  }

  const total = count ?? 0;

  return {
    data: {
      data: data ?? [],
      total,
      page,
      pageSize,
      totalPages: Math.ceil(total / pageSize),
    },
    error: null,
  };
}

export async function updateShipmentStatus(
  shipmentId: string,
  newStatus: ShipmentStatus
): Promise<ApiResponse<Shipment>> {
  const supabase = await createClient();

  const { data, error } = await supabase
    .from("shipments")
    .update({ status: newStatus })
    .eq("id", shipmentId)
    .select()
    .single();

  if (error) {
    return { data: null, error: { message: error.message, status: 500 } };
  }

  return { data, error: null };
}

/**
 * Public tracking lookup. Uses admin client (bypasses RLS) because
 * tracking is unauthenticated. Returns only non-sensitive fields —
 * no phone numbers, no customer profile, no payment data.
 */
export async function getPublicTrackingData(
  trackingId: string
): Promise<ApiResponse<PublicTrackingData>> {
  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from("shipments")
    .select(
      "tracking_id, status, created_at, parcel_size, delivery_mode, delivery_speed, carrier_name, carrier_tracking_number, origin_pickup_point:pickup_points!shipments_origin_pickup_point_id_fkey(name, city), destination_pickup_point:pickup_points!shipments_destination_pickup_point_id_fkey(name, city), scan_logs(new_status, scanned_at)"
    )
    .eq("tracking_id", trackingId)
    .order("scanned_at", { referencedTable: "scan_logs", ascending: true })
    .single();

  if (error || !data) {
    return {
      data: null,
      error: { message: "Shipment not found", code: "NOT_FOUND", status: 404 },
    };
  }

  return { data: data as unknown as PublicTrackingData, error: null };
}
