import type { Database } from "./database.types";
import type { DeliveryMode, DeliverySpeed, ParcelSize } from "./enums";

// ─── Database row types (auto-generated, do not hand-edit) ───────────────────

export type Shipment = Database["public"]["Tables"]["shipments"]["Row"];
export type ShipmentInsert = Database["public"]["Tables"]["shipments"]["Insert"];
export type ShipmentUpdate = Database["public"]["Tables"]["shipments"]["Update"];

export type ShipmentWithRelations = Shipment & {
  origin_pickup_point: Database["public"]["Tables"]["pickup_points"]["Row"];
  destination_pickup_point: Database["public"]["Tables"]["pickup_points"]["Row"];
  customer: Database["public"]["Tables"]["profiles"]["Row"];
  scan_logs: Database["public"]["Tables"]["scan_logs"]["Row"][];
};

// ─── Public tracking type (sanitized — no sensitive data) ────────────────────

export type PublicTrackingData = {
  tracking_id: string;
  status: string;
  created_at: string;
  parcel_size: string;
  delivery_mode: string;
  delivery_speed: string;
  carrier_name: string | null;
  carrier_tracking_number: string | null;
  origin_pickup_point: { name: string; city: string } | null;
  destination_pickup_point: { name: string; city: string } | null;
  scan_logs: { new_status: string; scanned_at: string }[];
};

// ─── Service input type ───────────────────────────────────────────────────────
// Used by shipment.service.ts → createShipment().
// customer_id is passed as a separate param (not part of this input).
// tracking_id is auto-generated by the DB trigger (excluded here).
// qr_code_url is set after QR generation (excluded here).

export type CreateShipmentInput = {
  // People
  sender_name: string;
  sender_phone: string;
  receiver_name: string;
  receiver_phone: string;
  // Locations
  origin_pickup_point_id: string;
  destination_pickup_point_id: string;
  origin_postcode: string;
  destination_postcode: string;
  // Parcel
  parcel_size: ParcelSize;
  weight_kg: number;
  billable_weight_kg: number;
  parcel_length_cm: number;
  parcel_width_cm: number;
  parcel_height_cm: number;
  // Delivery
  delivery_mode: DeliveryMode;
  delivery_speed: DeliverySpeed;
  // Pricing (snapshot at booking time — never recomputed after payment)
  price_cents: number;
  carrier_rate_cents: number | null;
  margin_percent: number | null;
  shipping_method_id: number | null;
  insurance_option_id: string | null;
  insurance_amount_cents: number;
  insurance_surcharge_cents: number;
  // Payment
  stripe_checkout_session_id: string;
  stripe_payment_intent_id: string | null;
};

// ─── Pricing types ────────────────────────────────────────────────────────────
// Represents one delivery speed option (standard or express).

export type PriceOption = {
  shippingCents: number; // carrier_rate * margin, or internal flat price
  carrierRateCents: number; // raw carrier rate (0 for internal routes)
  marginPercent: number; // margin applied (0 for internal routes)
  insuranceSurchargeCents: number; // extra cost above the included €25 tier
  subtotalCents: number; // shippingCents + insuranceSurchargeCents
  ivaCents: number; // 21% of subtotalCents
  totalCents: number; // subtotalCents + ivaCents
  shippingMethodId: number | null; // SendCloud method ID (null for internal)
  estimatedDays: string | null; // e.g. "2-3 días" (null for internal)
};

// Full price breakdown returned by the pricing engine and stored in booking store.
export type PriceBreakdown = {
  deliveryMode: DeliveryMode;
  billableWeightKg: number; // max(actual_weight, volumetric_weight)
  standard: PriceOption;
  express: PriceOption | null; // null for internal routes
  insuranceCoverageCents: number; // base coverage always included (2500 = €25)
};
