import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    SUPABASE_SERVICE_ROLE_KEY: z.string().min(1),
    SUPABASE_PUBLISHABLE_KEY: z.string().min(1).optional(),
    SUPABASE_PROJECT_ID: z.string().min(1).optional(),
    STRIPE_SECRET_KEY: z.string().startsWith("sk_").optional(),
    STRIPE_WEBHOOK_SECRET: z.string().startsWith("whsec_").optional(),
    GALLABOX_API_KEY: z.string().min(1).optional(),
    GALLABOX_API_SECRET: z.string().min(1).optional(),
    GALLABOX_API_URL: z.string().url().optional(),
    GALLABOX_CHANNEL_ID: z.string().min(1).optional(),
    GALLABOX_PHONE: z.string().min(1).optional(),
    SENDCLOUD_PUBLIC_KEY: z.string().min(1).optional(),
    SENDCLOUD_SECRET_KEY: z.string().min(1).optional(),
    ADMIN_WHATSAPP_PHONE: z.string().min(1).optional(),
    SEND_OWNER_INVITES: z.enum(["true", "false"]).optional(),
  },
  client: {
    NEXT_PUBLIC_SUPABASE_URL: z.string().url(),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().min(1),
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string().startsWith("pk_").optional(),
    NEXT_PUBLIC_APP_URL: z.string().url().optional(),
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: z.string().min(1),
  },
  runtimeEnv: {
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    SUPABASE_PUBLISHABLE_KEY: process.env.SUPABASE_PUBLISHABLE_KEY,
    SUPABASE_PROJECT_ID: process.env.SUPABASE_PROJECT_ID,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    GALLABOX_API_KEY: process.env.GALLABOX_API_KEY,
    GALLABOX_API_SECRET: process.env.GALLABOX_API_SECRET,
    GALLABOX_API_URL: process.env.GALLABOX_API_URL,
    GALLABOX_CHANNEL_ID: process.env.GALLABOX_CHANNEL_ID,
    GALLABOX_PHONE: process.env.GALLABOX_PHONE,
    SENDCLOUD_PUBLIC_KEY: process.env.SENDCLOUD_PUBLIC_KEY,
    SENDCLOUD_SECRET_KEY: process.env.SENDCLOUD_SECRET_KEY,
    ADMIN_WHATSAPP_PHONE: process.env.ADMIN_WHATSAPP_PHONE,
    SEND_OWNER_INVITES: process.env.SEND_OWNER_INVITES as "true" | "false" | undefined,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
